CHART_DIR = ../charts
TARGET_DIR = /media/sf_P/Dropbox/pymlbook/pmle/ch11

copy: 
	cp $(CHART_DIR)/corr_demo_1.png $(TARGET_DIR)/1400_11_01.png
	cp $(CHART_DIR)/corr_demo_2.png $(TARGET_DIR)/1400_11_02.png

	cp $(CHART_DIR)/entropy_demo.png $(TARGET_DIR)/1400_11_03.png
	cp $(CHART_DIR)/mi_demo_1.png $(TARGET_DIR)/1400_11_04.png
	cp $(CHART_DIR)/mi_demo_2.png $(TARGET_DIR)/1400_11_05.png

	cp $(CHART_DIR)/pca_demo_1.png $(TARGET_DIR)/1400_11_08.png
	cp $(CHART_DIR)/pca_demo_2.png $(TARGET_DIR)/1400_11_09.png
	cp $(CHART_DIR)/lda_demo.png $(TARGET_DIR)/1400_11_10.png

	cp $(CHART_DIR)/mds_demo_1.png $(TARGET_DIR)/1400_11_13.png
	cp $(CHART_DIR)/mds_demo_iris.png $(TARGET_DIR)/1400_11_11.png
	cp $(CHART_DIR)/pca_demo_iris.png $(TARGET_DIR)/1400_11_12.png
	
	cp *.py $(TARGET_DIR)/code
	cp Makefile $(TARGET_DIR)/code

